# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT

[files]
extend-exclude = [
]

[default.extend-identifiers]
cb9b62eb1979589daa18142008 = "cb9b62eb1979589daa18142008"
